create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(80) not null,
    email varchar(254) not null,
    password_hash varchar(100) not null,
    age integer not null,
    gender varchar(30) not null,
    phone_number varchar(30) not null,
    height integer not null,
    weight integer not null,
    exercise_experience varchar(50) not null,
    referrer varchar(80),
    created_at timestamp with time zone not null,
    active boolean not null default true
);

create unique index if not exists ux_users_email_lower on users (lower(email));
create unique index if not exists ux_users_phone_number on users (phone_number);